### ISSUE TITLE
Crash while right clicking to open dimdoors boot V2.2.5 test 6

### ISSUE THREAD

**Issue by crunkazcanbe** [CannibalVox/DimDoors#11]
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 3/15/15 12:27 AM
Description: Rendering screen

java.lang.AbstractMethodError
	at me.jezza.oc.client.gui.GuiContainerAbstract.func_146976_a(GuiContainerAbstract.java:98)
	at net.gtn.dimensionalpocket.client.gui.GuiInfoBook.func_146976_a(GuiInfoBook.java:102)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at me.jezza.oc.client.gui.GuiContainerAbstract.func_146976_a(GuiContainerAbstract.java:98)
	at net.gtn.dimensionalpocket.client.gui.GuiInfoBook.func_146976_a(GuiInfoBook.java:102)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)

**Comment by DPxKnightxZero** [comment]
Agreed

**Comment by CannibalVox** [comment]
what's a dimdoors boot

**Comment by crunkazcanbe** [comment]
the book bro my bad

**Comment by CannibalVox** [comment]
what's a dimdoors book

**Comment by crunkazcanbe** [comment]
My bad guys ... This is a crash from the dim pockets mods book
