### ISSUE TITLE
Rift key right-click server crash

### ISSUE THREAD

**Issue by chaoskagami** [CannibalVox/DimDoors#13]
Upon right clicking with a rift key (looking at a door, or not, in a pocket dimension, or not - basically doesn't matter) causes an immediate server crash. Stack dump:

Description: Exception in server tick loop
java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.func_71011_bu()Lnet/minecraft/item/ItemStack;
	at StevenDimDoors.mod_pocketDim.items.ItemDDKey.onItemUseFirst(ItemDDKey.java:85)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:360)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

This is also built from the source of the latest git revision, since I wanted the fix that was just committed and I like filing bug reports.

**Comment by CannibalVox** [comment]
can you get me the entire crash log?

**Comment by CannibalVox** [comment]
I'm really inclined to say that this is an error on your end because it's a NoSuchMethodError on a minecraft method

**Comment by chaoskagami** [comment]
I dunno. Also, we have time zone difference apparently, Let me get a log for you.

It's possible it's a compatibility thing with other mods, but I doubt it. I'll attempt to reproduce it in a minimal testcase and post up a log shortly.

**Comment by chaoskagami** [comment]
It also does it with test6 as well, so it's not how I built it from git.

**Comment by chaoskagami** [comment]
Okay, logs. I used just DD this time, nothing else. Server is on Windows x64, client is Linux x64. Both use OpenJDK (yes, windows can use openjdk - no, I won't use oracle's)

Logs here: https://gist.github.com/chaoskagami/767207ec47daa0ad089f

**Comment by chaoskagami** [comment]
Also of note is that a client opened to LAN doesn't have this issue, only a server and client running separately.

**Comment by keenerb** [comment]
I can duplicate on private server, canvox.

[09:59:29 ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.func_71011_bu()Lnet/minecraft/item/ItemStack;
	at StevenDimDoors.mod_pocketDim.items.ItemDDKey.onItemUseFirst(ItemDDKey.java:85) ~[ItemDDKey.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:436) ~[mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:875) ~[nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) ~[nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]

**Comment by CannibalVox** [comment]
Fixed in d01bbb488efd08a31e942cd43e22b230d5ccd21f

Thanks for reporting!
