### ISSUE TITLE
CLIENT crash restarting server with active client, Test8

### ISSUE THREAD

**Issue by keenerb** [CannibalVox/DimDoors#22]
http://pastie.org/10047906

I was in main overworld with a dimensional door nearby.  No other players on server, no one in a pocket dimension.

```
[B#283]  [15:29:31] [Netty Client IO #1/INFO] [STDOUT]: [StevenDimDoors.mod_pocketDim.core.PocketManager:unload:641]: Unloading Pocket Dimensions...
[B#283]  [15:29:35] [Client thread/INFO] [FML]: Applying holder lookups
[B#283]  [15:29:35] [Client thread/INFO] [FML]: Holder lookups applied
[B#283]  [15:29:38] [Client thread/FATAL]: Reported exception thrown!
[B#283]  net.minecraft.util.ReportedException: Ticking block entity
[B#283]  	at net.minecraft.world.World.func_72939_s(World.java:1954) ~[ahb.class:?]
[B#283]  	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1994) ~[bao.class:?]
[B#283]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) ~[bao.class:?]
[B#283]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
[B#283]  	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
[B#283]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
[B#283]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
[B#283]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
[B#283]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[B#283]  Caused by: java.lang.NullPointerException
[B#283]  	at StevenDimDoors.mod_pocketDim.core.PocketManager.getLink(PocketManager.java:667) ~[PocketManager.class:?]
[B#283]  	at StevenDimDoors.mod_pocketDim.tileentities.TileEntityRift.func_145845_h(TileEntityRift.java:65) ~[TileEntityRift.class:?]
[B#283]  	at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
[B#283]  	... 10 more
[B#283]  [15:29:38] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
[B#283]  // Would you like a cupcake?
[B#283]  
[B#283]  Time: 3/23/15 3:29 PM
[B#283]  Description: Ticking block entity
[B#283]  
[B#283]  java.lang.NullPointerException: Ticking block entity
[B#283]  	at StevenDimDoors.mod_pocketDim.core.PocketManager.getLink(PocketManager.java:667)
[B#283]  	at StevenDimDoors.mod_pocketDim.tileentities.TileEntityRift.func_145845_h(TileEntityRift.java:65)
[B#283]  	at net.minecraft.world.World.func_72939_s(World.java:1939)
[B#283]  	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1994)
[B#283]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
[B#283]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
[B#283]  	at net.minecraft.client.main.Main.main(SourceFile:148)
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#283]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#283]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#283]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#283]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by DPxKnightxZero** [comment]
Yeah I have had this happen too though I have no idea what caused it.
