### ISSUE TITLE
1.7.10 version, strange crash issue in MP

### ISSUE THREAD

**Issue by CliffracerX** [CannibalVox/DimDoors#31]
Seems to happen when someone goes through a dimensional door.  Only happens for people connected to the server, hosts can go through fine.
Note that this is being done via Hamachi/Lan, if that could matter at all.

`java.lang.IllegalArgumentException: Could not get provider type for dimension 3, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148)
	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:302)
	at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:160)
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:54)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147280_a(NetHandlerPlayClient.java:865)
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:32)
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1591)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by DPxKnightxZero** [comment]
No it has nothing to do with hamachi! This mod needs to be fixed.

**Comment by m31317015** [comment]
Plz fix this! I love this mod but this bug causes my friends to call me to delete this mod! This bug is a critical bug!

**Comment by DPxKnightxZero** [comment]
Yeah I am waiting on the same fix. The creator of Pokecube Thutmose said he knew how to fix it but he stopped talking to me.

**Comment by m31317015** [comment]
Well can you contact him again? Cuz I really hate playing with bugs when my friends are with me...

**Comment by DPxKnightxZero** [comment]
Actually I am getting sick of high and mighty coders and I am starting to learn Java hopefully someday I can help the less talented like I was and am.

**Comment by m31317015** [comment]
Well I now have no hope on this mod anymore, unless the author (original one, not this one) comes back. Good luck if you're going to fix it.

**Comment by DPxKnightxZero** [comment]
Oh yeah my friend notabadminer is fixing it.

**Comment by DPxKnightxZero** [comment]
https://github.com/notabadminer/DimDoors/releases

**Comment by m31317015** [comment]
yay awesome, plz help me to thx him

**Comment by CannibalVox** [comment]
I believe notabadminer might have fixed this- let me know if that's not the case.

**Comment by GribanovIvan** [comment]
Not fixed.
Persists here: https://www.curseforge.com/minecraft/mc-mods/dimensional-doors-legacy/files/4967772
