### ISSUE TITLE
Crash out of nothing - worked for week, now down

### ISSUE THREAD

**Issue by PumaBlack** [CannibalVox/DimDoors#53]
What does this mean?

Description: Exception in server tick loop

java.lang.NullPointerException: Dimensions can be pocket dimensions if and only if they have a parent dimension.
    at StevenDimDoors.mod_pocketDim.core.NewDimData.<init>(NewDimData.java:170)
    at StevenDimDoors.mod_pocketDim.core.PocketManager$InnerDimData.<init>(PocketManager.java:48)
    at StevenDimDoors.mod_pocketDim.core.PocketManager.registerPackedDimData(PocketManager.java:212)
    at StevenDimDoors.mod_pocketDim.saving.DDSaveHandler.unpackDimData(DDSaveHandler.java:134)
    at StevenDimDoors.mod_pocketDim.saving.DDSaveHandler.loadAll(DDSaveHandler.java:94)
    at StevenDimDoors.mod_pocketDim.core.PocketManager.loadInternal(PocketManager.java:390)
    at StevenDimDoors.mod_pocketDim.core.PocketManager.load(PocketManager.java:192)
    at StevenDimDoors.mod_pocketDim.EventHookContainer.onWorldLoad(EventHookContainer.java:124)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_63_EventHookContainer_onWorldLoad_Load.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:230)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:258)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

---

Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 3.13.0-66-generic
    Java Version: 1.7.0_71, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 300255888 bytes (286 MB) / 724566016 bytes (691 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 3 total; -Xms192M -Xmx1024M -XX:MaxPermSize=256M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492

Thanks in advance.

**Comment by P3rf3ctXZer0** [comment]
holy fuck ... that is a rare crash. Anyways its caused by a dimension corrupting. What were you doing when it crashed and if it was on a server; did the server crash a few times before this issue arose? 

This is what gives it away

"Dimensions can be pocket dimensions if and only if they have a parent dimension." 

The parent folder is corrupted somehow.
